import { useCallback, useEffect, useState } from 'react';
import { Bell, CheckCircle2, Clock3, Heart, History, IdCard, Mail, MapPin, Plus, Save, ShieldCheck, Ticket, Trash2, UserRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { catalogApi, type Attendee, type HistoryItem, type Profile, type Reminder } from '../../api/catalog';
import { orderApi } from '../../api/orders';
import type { Order } from '../../types';
import AccountSecurity from './AccountSecurity';
import Toast from '../../components/Toast';
import './PersonalCenter.css';

type Tab='profile'|'orders'|'tickets'|'favorites'|'history'|'attendees'|'reminders'|'security';
const tabs=[['profile','个人资料',UserRound],['orders','我的订单',Ticket],['tickets','电子票',IdCard],['favorites','收藏',Heart],['history','浏览历史',History],['attendees','常用观演人',UserRound],['reminders','开售提醒',Bell],['security','账号安全',ShieldCheck]] as const;
const statusText:Record<string,string>={PENDING:'待支付',CONFIRMED:'已确认',CANCELLED:'已取消',EXPIRED:'已过期',SENT:'已发送',FAILED:'发送失败',PROCESSING:'处理中'};

export default function PersonalCenter(){
 const [tab,setTab]=useState<Tab>('profile'),[profile,setProfile]=useState<Profile|null>(null),[orders,setOrders]=useState<Order[]>([]),[attendees,setAttendees]=useState<Attendee[]>([]),[history,setHistory]=useState<HistoryItem[]>([]),[reminders,setReminders]=useState<Reminder[]>([]),[favorites,setFavorites]=useState<any[]>([]),[message,setMessage]=useState(''),[error,setError]=useState('');
 const token=localStorage.getItem('token')||'';
 const load=useCallback(async()=>{try{setProfile(await catalogApi.profile());}catch(e){setError(e instanceof Error?e.message:'个人资料加载失败');return;} try{const [o,a,h,r,e]=await Promise.all([orderApi.getMyOrders(token),catalogApi.attendees(),catalogApi.history(),catalogApi.reminders(),catalogApi.home()]);setOrders(o);setAttendees(a);setHistory(h);setReminders(r);setFavorites(e.filter(x=>x.favorite));}catch(e){setError(e instanceof Error?e.message:'个人中心数据加载失败');}},[token]);
 useEffect(()=>{void load();},[load]);
 const save=async()=>{if(!profile)return;try{setProfile(await catalogApi.updateProfile(profile));setMessage('个人资料已更新');}catch(e){setError(e instanceof Error?e.message:'保存失败');}};
 const addAttendee=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{setAttendees(await catalogApi.addAttendee({name:String(f.get('name')),id_type:String(f.get('id_type')),id_number:String(f.get('id_number')),phone:String(f.get('phone')),is_default:f.get('is_default')==='on'}));e.currentTarget.reset();setMessage('观演人已添加');}catch(err){setError(err instanceof Error?err.message:'添加失败');}};
 const removeAttendee=async(id:number)=>{try{setAttendees(await catalogApi.deleteAttendee(id));setMessage('观演人已删除');}catch(e){setError(e instanceof Error?e.message:'删除失败');}};
 return <div className="personal-page"><Toast message={error||message} tone={error?'error':'success'} onClose={()=>{setError('');setMessage('');}}/>
  <header className="personal-head"><div className="profile-avatar"><img src={profile?.avatar_path||'/media/avatars/default.webp'} alt=""/></div><div><span>个人中心</span><h1>{profile?.display_name||profile?.username||'我的 HyperTicket'}</h1><p>{profile?.city||'未设置常驻城市'} · {profile?.email_verified?'邮箱已验证':'邮箱待验证'}</p></div></header>
  <nav className="personal-tabs" aria-label="个人中心功能">{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={17}/>{label}</button>)}</nav>
  {tab==='profile'&&profile&&<section className="personal-panel"><PanelTitle icon={UserRound} title="个人资料" detail="资料修改后立即生效"/><div className="profile-form"><label>显示名称<input value={profile.display_name} onChange={e=>setProfile({...profile,display_name:e.target.value})}/></label><label>常驻城市<input value={profile.city} onChange={e=>setProfile({...profile,city:e.target.value})}/></label><label>生日<input type="date" value={profile.birthday} onChange={e=>setProfile({...profile,birthday:e.target.value})}/></label><label>性别<select value={profile.gender} onChange={e=>setProfile({...profile,gender:e.target.value})}><option value="UNSPECIFIED">不设置</option><option value="MALE">男</option><option value="FEMALE">女</option></select></label><label className="wide">个人简介<textarea value={profile.bio} onChange={e=>setProfile({...profile,bio:e.target.value})}/></label></div><div className="contact-lines"><p><CheckCircle2 size={16}/>{profile.phone_verified?'手机号已验证':'手机号待验证'} · {profile.tel.slice(0,3)}****{profile.tel.slice(-4)}</p><p><Mail size={16}/>{profile.email_verified?'邮箱已验证':'邮箱待验证'} · {profile.email||'未绑定'}</p></div><button className="primary-action" onClick={save}><Save size={16}/>保存资料</button></section>}
  {tab==='orders'&&<section className="personal-panel"><PanelTitle icon={Ticket} title="我的订单" detail={`${orders.length} 笔订单`}/><OrderRows rows={orders}/><Link className="text-link" to="/customer/orders">进入订单管理与支付</Link></section>}
  {tab==='tickets'&&<section className="personal-panel"><PanelTitle icon={IdCard} title="我的电子票" detail="已支付订单可用于入场"/><OrderRows rows={orders.filter(x=>x.status==='CONFIRMED')} ticket/></section>}
  {tab==='favorites'&&<section className="personal-panel"><PanelTitle icon={Heart} title="我的收藏" detail={`${favorites.length} 个想看的活动`}/><div className="simple-grid">{favorites.map(e=><Link to="/customer" key={e.event_id}><img src={e.cover_path} alt=""/><b>{e.title}</b><span>{e.city} · {e.venue_name}</span></Link>)}</div></section>}
  {tab==='history'&&<section className="personal-panel"><PanelTitle icon={History} title="浏览历史" detail="最近查看的活动"/><div className="history-list">{history.map(h=><div key={h.event_id}><img src={h.cover_path} alt=""/><span><b>{h.title}</b><small>查看 {h.view_count} 次 · {h.last_viewed_at}</small></span></div>)}</div></section>}
  {tab==='attendees'&&<section className="personal-panel"><PanelTitle icon={UserRound} title="常用观演人" detail="实名活动下单时使用"/><div className="attendee-list">{attendees.map(a=><div key={a.attendee_id}><IdCard/><span><b>{a.name}{a.is_default&&<em>默认</em>}</b><small>{a.id_type} · {a.id_number_masked} · {a.phone_masked}</small></span><button onClick={()=>removeAttendee(a.attendee_id)} aria-label="删除观演人"><Trash2 size={16}/></button></div>)}</div><form className="attendee-form" onSubmit={addAttendee}><input name="name" placeholder="姓名" required/><select name="id_type"><option value="PRC_ID">居民身份证</option><option value="PASSPORT">护照</option><option value="HK_MACAO_PERMIT">港澳通行证</option><option value="TAIWAN_PERMIT">台湾通行证</option></select><input name="id_number" placeholder="证件号码" required/><input name="phone" placeholder="手机号（选填）"/><label><input type="checkbox" name="is_default"/>设为默认</label><button className="primary-action"><Plus size={16}/>添加观演人</button></form></section>}
  {tab==='reminders'&&<section className="personal-panel"><PanelTitle icon={Bell} title="开售提醒" detail="通过已验证邮箱发送"/><div className="reminder-list">{reminders.map(r=><div key={r.reminder_id}><Clock3/><span><b>{r.title}</b><small>{r.remind_at}</small></span><Status value={r.status}/>{['PENDING','FAILED'].includes(r.status)&&<button onClick={async()=>setReminders(await catalogApi.cancelReminder(r.reminder_id))}>取消</button>}</div>)}</div></section>}
  {tab==='security'&&<AccountSecurity/>}
 </div>;
}
function PanelTitle({icon:Icon,title,detail}:{icon:any;title:string;detail:string}){return <header className="panel-title"><Icon size={20}/><div><h2>{title}</h2><p>{detail}</p></div></header>}
function Status({value}:{value:string}){return <span className={`status-pill status-${value.toLowerCase()}`}>{statusText[value]||value}</span>}
function OrderRows({rows,ticket=false}:{rows:Order[];ticket?:boolean}){return <div className="order-rows">{rows.map(o=><div key={o.id}><span><b>{o.title}</b><small>{o.event_date} · {o.venue} · {o.seat_label||`${o.quantity} 张`}</small></span><Status value={o.status}/>{ticket&&<Link to="/customer/orders">查看入场票</Link>}</div>)}</div>}
